"""
.. module:: bin3d
    :synopsis: Functions for reading/writing xcompact3d binary data.
.. moduleauthor:: Paul Bartholomew <ptb08@ic.ac.uk>
"""

import numpy as np

def read_i3d_data(filename, nx, ny, nz, dtype=np.float64):
    """ Reads a datafile generated by Incompact3D into a (3D) numpy array. 

    :param filename: The file to read.
    :param nx: The mesh x resolution.
    :param ny: The mesh y resolution.
    :param nz: The mesh z resolution.
    :param dtype: """

    N = nx * ny * nz
    with open(filename, "rb") as bindat:
        fldat = np.fromfile(bindat, dtype)
    assert(len(fldat) == N)

    return np.reshape(fldat, (nx, ny, nz), "F")

def write_i3d_data():
    """ Writes a (3D) numpy array to an Incompact3D style data file. """
    raise NotImplementedError
